#![allow(unused)]
#![feature(box_syntax, box_patterns)]

pub mod base;

pub mod add_to_array_form_of_integer;
pub mod arranging_coins;
pub mod array_partition_i;
pub mod baseball_game;
pub mod beautiful_arrangement;
pub mod beautiful_arrangement_ii;
pub mod beautiful_array;
mod best_time_to_buy_and_sell_stock;
mod best_time_to_buy_and_sell_stock_ii;
pub mod best_time_to_buy_and_sell_stock_iii;
pub mod best_time_to_buy_and_sell_stock_with_cooldown;
mod binary_gap;
mod binary_tree_maximum_path_sum;
pub mod can_i_win;
pub mod coin_change;
pub mod convert_a_number_to_hexadecimal;
mod count_and_say;
pub mod count_primes;
pub mod counting_bits;
pub mod custom_sort_string;
pub mod defanging_an_ip_address;
pub mod di_string_match;
pub mod divide_two_integers;
pub mod divisor_game;
pub mod fibonacci_number;
pub mod find_common_characters;
pub mod find_pivot_index;
pub mod find_words_that_can_be_formed_by_characters;
mod friend_circles;
pub mod group_anagrams;
pub mod hamming_distance;
pub mod height_checker;
pub mod increasing_order_search_tree;
pub mod insert_into_a_binary_search_tree;
pub mod intersection_of_two_arrays;
pub mod intersection_of_two_arrays_ii;
pub mod island_perimeter;
mod isomorphic_strings;
pub mod jump_game;
pub mod jump_game_ii;
mod keyboard_row;
pub mod kth_largest_element_in_a_stream;
pub mod last_stone_weight;
pub mod last_stone_weight_ii;
pub mod leaf_similar_trees;
pub mod length_of_last_word;
pub mod license_key_formatting;
pub mod longest_arithmetic_sequence;
pub mod longest_consecutive_sequence;
pub mod longest_continuous_increasing_subsequence;
pub mod longest_harmonious_subsequence;
pub mod longest_increasing_subsequence;
pub mod longest_palindromic;
pub mod longest_palindromic_substring;
mod longest_univalue_path;
pub mod majority_element;
pub mod matrix_cells_in_distance_order;
pub mod maximize_distance_to_closest_person;
pub mod maximum_binary_tree;
pub mod maximum_binary_tree_ii;
pub mod maximum_length_of_repeated_subarray;
pub mod maximum_product_subarray;
mod maximum_subarray;
pub mod merge_intervals;
pub mod merge_sorted_array;
pub mod merge_two_binary_trees;
pub mod merge_two_sorted_lists;
pub mod middle_of_the_linked_list;
pub mod minimum_absolute_difference;
pub mod minimum_absolute_difference_in_bst;
pub mod minimum_cost_for_tickets;
mod minimum_depth_of_binary_tree;
pub mod most_common_word;
pub mod moving_stones_until_consecutive;
mod n_repeated_element_in_size_2n_array;
pub mod nth_digit;
pub mod number_complement;
pub mod number_of_longest_increasing_subsequence;
pub mod number_of_recent_calls;
pub mod palindromic_substrings;
mod path_sum;
mod path_sum_iii;
pub mod peak_index_in_a_mountain_array;
pub mod perfect_number;
pub mod permutation_sequence;
pub mod permutations;
pub mod permutations_ii;
pub mod powerful_integers;
pub mod powx_n;
pub mod range_sum_of_bst;
pub mod range_sum_query_mutable;
pub mod relative_sort_array;
pub mod remove_duplicates_from_sorted_list;
pub mod remove_nth_node_from_end_of_list;
pub mod reverse_vowels_of_a_string;
pub mod reverse_words_in_a_string;
pub mod reverse_words_in_a_string_iii;
pub mod rotate_array;
pub mod rotate_image;
pub mod rotate_list;
pub mod search_in_rotated_sorted_array;
mod search_insert_position;
pub mod second_minimum_node_in_a_binary_tree;
pub mod self_dividing_numbers;
pub mod set_matrix_zeroes;
pub mod single_number;
pub mod single_number_ii;
pub mod single_number_iii;
pub mod sliding_window_maximum;
pub mod smallest_range_i;
pub mod sort_an_array;
pub mod sort_array_by_parity;
pub mod sort_array_by_parity_ii;
pub mod sort_colors;
pub mod spiral_matrix;
pub mod spiral_matrix_ii;
pub mod spiral_matrix_iii;
pub mod split_a_string_in_balanced_strings;
pub mod squares_of_a_sorted_array;
pub mod stone_game;
pub mod subdomain_visit_count;
pub mod subsets;
pub mod subtree_of_another_tree;
pub mod sum_of_two_integers;
mod sum_root_to_leaf_numbers;
pub mod super_egg_drop;
mod surface_area_of_3d_shapes;
pub mod swap_nodes_in_pairs;
pub mod top_k_frequent_elements;
pub mod triangle;
pub mod ugly_number_ii;
mod unique_email_addresses;
pub mod unique_morse_code_words;
pub mod unique_paths;
pub mod unique_paths_ii;
mod univalued_binary_tree;
pub mod valid_anagram;
pub mod valid_perfect_square;
pub mod valid_sudoku;
pub mod word_pattern;
pub mod word_search;
pub mod zigzag_conversion;
pub mod maximum_product_of_three_numbers;
pub mod decode_ways;
pub mod convert_binary_number_in_a_linked_list_to_integer;
pub mod detect_capital;
pub mod average_salary_excluding_the_minimum_and_maximum_salary;
pub mod add_two_numbers_ii;
pub mod matrix_01;
pub mod minimum_size_subarray_sum;
pub mod two_keys_keyboard;
pub mod additive_number;
pub mod split_array_into_fibonacci_sequence;
pub mod one_bit_and_two_bit_characters;
pub mod gray_code;
pub mod array_of_doubled_pairs;
pub mod insertion_sort_list;