#![feature(vec_remove_item, box_syntax, box_patterns)]

pub mod base;

pub mod array_partition_i;
pub mod baseball_game;
mod best_time_to_buy_and_sell_stock;
mod best_time_to_buy_and_sell_stock_ii;
pub mod best_time_to_buy_and_sell_stock_with_cooldown;
mod binary_gap;
mod binary_tree_maximum_path_sum;
mod count_and_say;
pub mod count_primes;
pub mod di_string_match;
pub mod divisor_game;
pub mod find_common_characters;
mod friend_circles;
pub mod hamming_distance;
pub mod insert_into_a_binary_search_tree;
mod isomorphic_strings;
mod keyboard_row;
pub mod longest_palindromic_substring;
mod longest_univalue_path;
pub mod maximum_binary_tree;
pub mod maximum_binary_tree_ii;
mod maximum_subarray;
pub mod merge_sorted_array;
pub mod merge_two_binary_trees;
pub mod merge_two_sorted_lists;
mod minimum_depth_of_binary_tree;
mod n_repeated_element_in_size_2n_array;
pub mod number_complement;
pub mod ones_and_zeroes;
mod path_sum;
mod path_sum_iii;
pub mod peak_index_in_a_mountain_array;
pub mod permutations;
pub mod range_sum_of_bst;
pub mod remove_nth_node_from_end_of_list;
pub mod reverse_words_in_a_string_iii;
mod search_in_a_binary_search_tree;
pub mod search_in_rotated_sorted_array;
mod search_insert_position;
pub mod self_dividing_numbers;
pub mod smallest_range_i;
pub mod sort_array_by_parity_ii;
pub mod split_array_largest_sum;
pub mod stone_game;
pub mod sum_of_two_integers;
mod sum_root_to_leaf_numbers;
mod surface_area_of_3d_shapes;
pub mod swap_nodes_in_pairs;
pub mod top_k_frequent_elements;
mod unique_email_addresses;
pub mod unique_morse_code_words;
pub mod unique_paths;
mod univalued_binary_tree;
pub mod valid_anagram;
pub mod rotate_array;

